# Generated by Django 4.2.2 on 2023-06-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
